#include <iostream>
#include <DartVMHelper.h>
#include "version.h" // Header auto-generated by cmake

int main(int argc, char *argv[])
{
	if (argc > 0)
		std::cout << std::endl << "Program " << argv[0] << " version: " << Example_VERSION_MAJOR << "." << Example_VERSION_MINOR << "." << Example_VERSION_PATCH << std::endl << std::endl;

	if(InitSystem("Test") == 0)
	{
		std::cout << "DLL Init Ok" << std::endl;
	}

	DeinitSystem();
	
	return 0;
}